#Complementing a Strand of DNA

seq = 'GGAGCTGGCTACGTACGGAGGGAGAAATCTAGGCACCACTTGGAATTTTTATAGAGAGGCCACACCGCTGCCAGCACGGGGGGGATAGCATGTCTTTTAAGTAGTGGGGCGGCGAGGACGTATGGCTGACACGGGTCATCGTTGCACGAGGGTGCTTTCACCCCACCCTAAAGGCTGCCAGTAGGGCAGCGTGCTGGACTCATATTCACCGGGACCTAATGACATGCGTGGCGCTGTTGAACGACGTTACGTGACAAGAGAGAGCAGTATGGAAAGGCGCTGGACAAGCGACGTTTACTTTGTGCAGGCACATAGGCGGTATCGACACTTATCAACGACGACCACGATAGTGCGTTGGATGTGTTTAAGTAAACGGGCTTTTGCCCCGGAATGATGCGATTGTAACTATACAGGCGGAAATATCACGGCGACGGTCGCATATTCGTCTCATACTTGCCGTCGTTGACGGATAGCAAAAACTAGTACTATTTGCAAATGAAGTCCTGAGCCGCGGGCGAGCCCGCGTGCGACTTCGCACACCGGGTGAGGACGCCTTAAATAAGCCGATTTAGTCCAATTATTACTGGAAGTCCAGGAGCGTAACGTCATCCTCAATTGCGTATCTGCGGAGTCTTCATATTATTTCACACAGATACGGTAGGGTGGACATAAAGATAACAAGACACAAAGTATTGCTATACACGGGGACGGGGGGTAGTGTGACAGTAGTTCTCGTCCATAGTTTTTTCTTGTTCAGATCGGCGGTGGTTATGCACGCAAATTTTAGCCAACACACAAGCTGTGCCGCACCAAAACCGGCGGTGCAATCGAGCCGGAACGTGAGGAACTTAAGGGGGCTAAGTCGACGATTTGAGGATAACAAAAAATGCCCCCCAGGGTAAGATTACGTGCAATTATCACCCATCCGTAACAAGATTATGCTTGTTGTATTGAGCTAGAGTCCATT'
seq = seq[::-1]
bp = ''
for i in seq:
    if i =='A':
        bp += 'T'
    elif i =='C':
        bp += 'G'
    elif i =='G':
        bp +='C'
    elif i =='T':
        bp+='A'
print(bp)