#Counting DNA Nucleotides

sequence = 'GTCGGTAATCTTGCGGGTTCTCAGCCGAGTGTATTTCGTGTCAGCGCTGAAACCGCACGGTATTCACTCTTCATCGAATCTCGAAGTTCGGGCCTAGCCTTGGAGGTTGATCTAATAATTGATACAGGTGTAAATTCTATTCCGTGTTCTCACGCCTCAAACTATGTCTAAACACCTGTTGTAGTGGCTCACTTGCCCGTTAGACCGGATAGAGATATGAGTTCCCCGCAGTTCATATCGCAGATGTGCCGGTCACACAGGAAGATTACGACGTCTTGACACTGCATGGGAAAGTGGCTAACACAGAATGAAAGCGGCGTACAGTTAGCATTCTCCGACCTTACGAAGTTGATTTCTTACGACTGTATTTCAGGATTTGTTAAGGAGAAAGTAAATTTTCGTGGCTCAGCGGTAGTTGTGTCTATAAGATTGGACGGAGGTCACGGCTAACCGGAGTACAGTTAAATGAGTGCCCCAAATGTTGACTGGGTCGCTTAATGTTCAACTGCGGAGCTTACTTACGGACGCGAGTTTTGCGTAAACCGTGGGCCGTTTCTGGGCCAGATATATCGCCGCATATAGCACGCAGCCTGTATAAGCTGTTGAGTGTTGAGTTTAACAAAGCGGTCGAGACACAGGGCGGATTTTAACATCGTGGGGCTGATAAGAGCGCAGATACTATATTCAGTATCCGAGGCGCTGGACGACGATCCAGGCTATACAAACATAGTGTCCGGTCGTTTCGCTCTTTGCAAGTAAGTTTTTTAAATAGTTAAACGCGGTAGTGAACTCAGCGTTTTGGTTAGCAGAAAGGGGGCCGTGAATATGCGACTGGACTCTCCGCGTAGTGCGCCGATTAACCCTGGATCACTTAGTCCAGGTCAGGCTATCCA'
a = 0
c = 0 
g = 0 
t = 0
for s in sequence:
    if s =='A':
        a += 1
    elif s == 'C':
        c += 1
    elif s == 'G':
        g += 1
    elif s == 'T':
        t += 1
print(a,c,g,t)